version: '3'
services:
  tf-extras:
    image: sdavidhdez/docker-tensorflow-py3-extras:latest
    restart: always
    container_name: 'tf-extras'
    ports:
      - '8888:8888'
    volumes:
      - './notebooks:/notebooks'
      - './volumes/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py'
