version: '3.8'
services:
    ml-py3:
        image: sdavidhdez/ml-py3:latest
        restart: always
        container_name: 'ml-py3'
        ports:
            - '8888:8888'
        volumes:
            - './volumes/notebooks/:/home/jupyterlab/app/notebooks'
            - './volumes/shared-space/:/home/jupyterlab/shared-space'
        environment:
            - VIRTUAL_HOST=jupyter.totum.one
            - VIRTUAL_PORT=8888
            - LETSENCRYPT_HOST= 'jupyter.totum.one'

networks:
    default:
        external:
            name: webproxy
